device: cuda:0
note: "large-ext"
seed: 42
log_tensorboard: false
num_threads: 5


model_name: trans_linformerExt
model_kwargs:
  pe_type: learned
  num_heads: 8
  h_dim: 24
  n_layers: 6
  num_w_per_dist: 10
  # Linformer-specific
  max_seq_len: 15000
  compressed: 100
  proj_dim: 150

loss_name: focal_bce_logits
loss_kwargs:
  gamma: 1.5
  alpha_pos: 0.35        # set from train counts
  label_smoothing: 0.05
  reduction: mean


optimizer_name: adam
num_epochs: 200
batch_size: 4
optimizer_kwargs:
  lr: 1.0e-3


lr_scheduler_name: step
lr_scheduler_kwargs:
  gamma: 0.5
  step_size: 50


data_dir: /j-jepa-vol/HEPT-Zihan/data/
dataset_name: pileup
main_metric: auc
mode: max



